tags:
  [ 
  {
  frame: "tag_7",
  id: 7,
  corners: [
  [-0.100,  0.100, 0.0],
  [0.100,  0.100, 0.0],
  [0.100, -0.100, 0.0]
  ]
  },   
  {
  frame: "tag_1",
  id: 1,
  corners: [
  [-0.100,  0.100, 0.0],
  [0.100,  0.100, 0.0],
  [0.100, -0.100, 0.0]
  ]
  },   
  ]
bundles:
  [
  ]

# Marker corner order:
# 1          2
#  HD########
#  #ID#  ####
#  ##  ##  ##
#  ####  ####
#  ##########
# 4          3
